services:
  - type: web
    name: animelove
    env: node
    nodeVersion: 18
    plan: free
    buildCommand: npm i && npm run build
    startCommand: node server.js
    # Автоматическое развертывание при изменениях в репозитории
    repo: https://github.com/Migetsu/animelove.git
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ID
        value: XpCddxtIwd3GA26uhftF-EFxEaSXG-bsUosO9ll65mQ
      - key: CLIENT_SECRET
        sync: false
      - key: PORT 
        value: 10000
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: animelove
          type: web
          property: url
      - key: GITHUB_PAGES_URL
        value: https://migetsu.github.io/animelove
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"